export const homeObjOne = {
    id: 'capabilities',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "NEXT-GENERATION INTEGRATIONS",
    headline: "You Dream It, VM.Crystalware builds it.",
    description: "Design high-ranking professional websites, widgets, and databases to suit your business needs.",
    buttonLabel: 'Browse Packages Below',
    imgStart: false,
    img: require('../../images/rome.jpg').default,
    alt: 'romequote',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'packages',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Powerful and Built to Last",
    headline: "Bronze & Silver",
    description: "Need something simple? No problem! We even have an advanced, dynamic pack with features such as PT Everywhere cloud and schdeule integration just for you.",
    imgStart: false,
    img: require('../../images/bands.jpg').default,
    alt: 'bronze-and-silver-img',
    dark: true,
    buttonLabel: 'Tier 1 & 2',
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'gc',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Sleek, Efficient, and Oh Far So Ahead of The Game!",
    headline: "Gold & Crystal",
    description: "This is for those who want a seat at the top. Have your website house it's own Advanced next-Gen tech you'd think only existed on Star Trek. We're talking private databases, AI Bots, Video Conferencing, and more!",
    buttonLabel: 'Tier 3 & 4',
    imgStart: false,
    img: require('../../images/gold.jpg').default,
    alt: 'gold-and-crystal-img',
    dark: true,
    primary: true,
    darkText: false,
};